### ISSUE TITLE
Can't display my pictures

### ISSUE THREAD

**Issue by iamophaniel** [kapsolas/MMM-Flickr#4]
hello,

I don't understand how to display my pics with your module.
I downloaded and installed it. 
I added it in the config.js file with my user_ID (but I had to remove the "size part"; cause jslint.com spotted an error with it)
and now on my magic mirror there is only "Loading" and no picture while my clock (for example) is still working.

It's my first project and I don't understand how to fix this could you help me please ?

**Comment by wbleek** [comment]
Hello,
I actually have the same issue. Other social media integrations need a token or key to access the content. Maybe Yahoo changed the way you can access Flickr pictures.
Could @kapsolas please help debugging this issue? Thanks!
Wgb

**Comment by c-m0s** [comment]
Same here. I found the missing coma in the example, but the module is not desplaying any flickr-account I do try. 
Size: 'o' - original doesn't help.

frustrating.
Please help, @kapsolas 

Acctually, your Instagram-Module seems to have the same issues.

**Comment by kapsolas** [comment]
Sorry for the delay, had to find my raspberry pi with this deployed.

I reviewed by config and see that I don't actually use the size option. Can you try to remove it and see if it helps? 

The config should be:

```
{
	module: 'MMM-Flickr',
	position: 'top_right',
	config: {
		id: 'user_id_of_user_whose_photostream_to_view',
		animationSpeed: 2500,
		updateInterval: 10000
	}
},
```

**Comment by c-m0s** [comment]
Thanks, @kapsolas for looking into this-
But this didn't change anything for me (having a sizing function would be helpful though).
I do get a "Loading..." String only.
With which photostream-ID are you testing your plugin?

**Comment by c-m0s** [comment]
Hi @kapsolas-

it's working now.  I can't really say what changed- but now I do get the images from the Flickr Account. Thanks for your support!

```
{
	module: 'MMM-Flickr',
	position: 'middle_center', //'lower_third',
	config: {
			id: 'user_id_of_user_whose_photostream_to_view',
			animationSpeed: 2500,
			updateInterval: 10000,
			size: 'b' 
		  }
}
```

**Comment by kapsolas** [comment]
Awesome! Glad to hear it's working now! 

I haven't meet able to track down why it works for some and not for others.

**Comment by kapsolas** [comment]
Closing because of age.
