### ISSUE TITLE
Error in your example

### ISSUE THREAD

**Issue by YannickRiouRobotics** [kapsolas/MMM-Flickr#5]
I found that there is an error in your module example for the config.js file, it should be : 

`{
	module: 'MMM-Flickr',
	position: 'top_right',
	config: {
		id: 'user_id_of_user_whose_photostream_to_view',
		animationSpeed: 2500,
		updateInterval: 10000
		size: 'm' // Default is m, can be o=original, t=thumbnail, s= 75x75, b=1024
		          // 'z' medium 640, 640 on longest side. 'c' medium 800, 800 on longest side
	}
},`

The lack of the comma cause an error in the config file !

**Comment by YannickRiouRobotics** [comment]
The example throw also a Error 404 on the MagicMirror console...

**Comment by kapsolas** [comment]
Thanks for the update! I'll treat this as closed.
