### ISSUE TITLE
Module works, but ID is not Flickr UserName

### ISSUE THREAD

**Issue by FluxOtto** [kapsolas/MMM-Flickr#6]
for example if you want user 'spacex', then use this web page to find Flickr ID:
https://www.webpagefx.com/tools/idgettr/
and user 'spacex' is i

id: '130608600@N05'

The config description hints at this, and that it will be updated in future. But I think just a few more words would help new users a lot.

**Comment by sajuran123** [comment]
Thank you!

**Comment by PeterEggs** [comment]
When I tried to set up the MMM-Flickr , its appeared , however , that’s not my photoed in Flickr Album , how can I solve it ,
below is the config.js :
module: ‘MMM-Flickr’,
position: ‘top_left’,
config: {
id: 'XXXXXXXXX',
animationSpeed: 2500,
updateInterval: 10000,
size: ‘m’ // Default is m, can be o=original, t=thumbnail, s= 75x75, b=1024
// ‘z’ medium 640, 640 on longest side. ‘c’ medium 800, 800 on longest side

Should I need to add the URL
full link of my album is :
https://www.flickr.com/photos/XXXXXXXXXX/albums/YYYYYYYYYY
id get from the idGettr
http: //www.flickr.com/photos/XXXXX
id : ZZZZZZZZZZ

**Comment by PeterEggs** [comment]
Solved , its need the photo album page of yours URL , not just your name URL , sothat you have a correct iGettr id
